# Generated by Django 4.2.3 on 2024-12-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_alter_user_managers_remove_user_capsule_media_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capsulemedia",
            name="location",
        ),
    ]
